### PR TITLE
changed buf size, added custom input function, added partition tool c…

### PR DESCRIPTION
**Pull request by Dfmaaa**
…onfirmation

The size of buf was 256, but the valid inputs were "1" and "2" , and other invalid inputs with n length. So I added a custom input function that uses getchar to fill the character array, and only scans len characters, which in this case is 1. So it will only scan the first character of input. I also added a confirmation, So that if the user enters something by mistake, they can just type N, and then enter the correct choice.

### CODE REVIEW

**Comment by Dfmaaa** [comment]
Also, if you want, I can add confirmation for other inputs too

**Comment by AntaresMKII** [comment]
You are not wrong. This solution is better. I was planning to revisit the user input handling a bit later since the project is still in early phase of development but it's all right doing it now. I'm going to test this later.

A criticism that I have of your code is that it doesn't follow the established style. It is usually best practice when contributing to other people's code to follow their style to maintain consistency.

**Comment by Dfmaaa** [comment]
what

**Comment by AntaresMKII** [comment]
By style I mean how the code is written. Like for example i usually write if statements like this:
`if (a == b) {
    printf(a);
}`
You can look at my code to see how I usually write things. This is just to keep things consistent and readable. If you can adapt your code to follow the style I'm going to merge your code to main branch or I can do it if you prefer.

**Comment by AntaresMKII** [comment]
Yep. That's the goal. It should look all the same. It's better for readability and consistency.
I'm going to merge you request soon.

**Pull request merged**
